#!/bin/bash
relaciona(){
    BANCO='database/banco.db'    
    tabelas=($(sqlite3 $BANCO ".table"))
    tabela=${tabelas[0]}
    relacao=${tabelas[1]}
    tabela=${tabela:1}
    relacao=${relacao:1}

    sqlite3 $BANCO "PRAGMA FOREIGN_KEYS=on"
    sqlite3 $BANCO  "CREATE TABLE ${tabela}_${relacao} ( 
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    ${tabela}_id INTEGER, 
                    ${relacao}_id INTEGER, 
                    FOREIGN KEY (${tabela}_id) REFERENCES ${tabela}(id), 
                    FOREIGN KEY (${relacao}_id) REFERENCES ${relacao}(id))"
   sqlite3 $BANCO "INSERT INTO ${tabela}_${relacao} VALUES (null, 1,1 )"
   sqlite3 $BANCO "INSERT INTO ${tabela}_${relacao} VALUES (null, 1,7 )"
   sqlite3 $BANCO "INSERT INTO ${tabela}_${relacao} VALUES (null, 5,2 )"
   sqlite3 $BANCO "INSERT INTO ${tabela}_${relacao} VALUES (null, 2,3 )"
   sqlite3 $BANCO "INSERT INTO ${tabela}_${relacao} VALUES (null, 3,5 )"
   sqlite3 $BANCO "INSERT INTO ${tabela}_${relacao} VALUES (null, 7,3 )"

   sqlite3 -column -header $BANCO "CREATE VIEW vRelacao AS SELECT * FROM  ${tabela} 
   JOIN ${tabela}_${relacao}
   ON ${tabela}.id=${tabela}_${relacao}.${tabela}_id 
   JOIN ${relacao} 
   ON ${relacao}.id=${tabela}_${relacao}.${relacao}_id" 
}
relaciona
