#!/usr/bin/env bash

BANCO='../database/agenda.db'
TABELA='login'
source ../Lib/_crud

_encrypt(){
    senha=$(echo "$@" | shasum | cut -d' ' -f1) 
}

cadastrar(){
  read -p "Digite o login: " login
  echo
  read -s -p  "Digite a senha: " senha
  echo
  read -s -p  "Confirmar: " 
  echo
  [ -n "$senha" -a "$senha" == "$REPLY"  ] || {
    echo  "Senha invalida"
    return 1
  }
  _encrypt "$senha"
  sql="INSERT INTO $TABELA (login, senha) VALUES ( '$login', '$senha')"
  sqlite3 "$BANCO" "$sql"
  sqlite3 -column -header $BANCO "SELECT *  FROM $TABELA WHERE login='$login'"
}

cadastrar
