#!/bin/bash
tabelas=$(mktemp)

relaciona(){
    BANCO='../database/banco.db'    
    tabelas=($(sqlite3 "$BANCO" '.table'))

    local tabela=${tabelas[1]:2}
    local relacao=${tabelas[0]:2}

    local relacionamento=${tabela}
    relacionamento+=_${relacao}

    sqlite4 $BANCO "CREATE TABLE ${relacionamento} ( 
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    ${tabela}_id INTEGER, 
                    ${relacao}_id INTEGER, 
                    FOREIGN KEY (${tabela}_id) REFERENCES ${tabela}(id), 
                    FOREIGN KEY (${relacao}_id) REFERENCES ${relacao}(id))"
                  
   echo "$(date +'%Y-%m-%d %H:%M') : Criado a tabela ${relacionamento}" > ../log/$(echo ${relacionamento})-log

   sqlite3 $BANCO "INSERT INTO ${relacionamento} VALUES (null, 1,1 )"
   sqlite3 $BANCO "INSERT INTO ${relacionamento} VALUES (null, 1,7 )"
   sqlite3 $BANCO "INSERT INTO ${relacionamento} VALUES (null, 5,2 )"
   sqlite3 $BANCO "INSERT INTO ${relacionamento} VALUES (null, 2,3 )"
   sqlite3 $BANCO "INSERT INTO ${relacionamento} VALUES (null, 3,5 )"
   sqlite3 $BANCO "INSERT INTO ${relacionamento} VALUES (null, 7,3 )"

  

   sqlite3 -column -header $BANCO "CREATE VIEW ${relacionamento:+v$relacionamento} AS SELECT * FROM
   ${tabela:+t_$tabela} 
   JOIN ${relacionamento}
   ON ${tabela:+t_$tabela}.id=${relacionamento}.${tabela}_id 
   JOIN ${relacao:+t_$relacao} 
   ON ${relacao:+t_$relacao}.id=${relacionamento}.${relacao}_id" 

   echo "$(date +'%Y-%m-%d %H:%M') : Criado a view ${relacionamento:+v$relacionamento}" >> ../log/$(echo ${relacionamento})-log
   sqlite3 -column -header $BANCO "SELECT * FROM ${relacionamento:+v$relacionamento}" >> ../log/$(echo ${relacionamento})-log
}
relaciona




