#!/bin/bash
tabelas=$(mktemp)
relaciona(){
    BANCO='database/banco.db'    
    sqlite3 "$BANCO" ".table" | sed 's/ /\n/g' | grep '^t' > "$tabelas"

    #read -p "Escolha as tabelas $(cat $tabelas | sed 's/\n/ /g') para relacionar: " tab_1 tab_2

    #echo  "tabelas selecionadas $tab_1 e  tabela $tab_2"
    #return
    relacionamento=${tabela:2}
    relacionamento+=_${relacao:2}

   # sqlite3 $BANCO "PRAGMA FOREIGN_KEYS=on"
   # sqlite3 $BANCO 
   echo  "CREATE TABLE ${relacionamento} ( 
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    ${tabela}_id INTEGER, 
                    ${relacao}_id INTEGER, 
                    FOREIGN KEY (${tabela}_id) REFERENCES ${tabela}(id), 
                    FOREIGN KEY (${relacao}_id) REFERENCES ${relacao}(id))"
                  
  return

   echo "$(date +'%Y-%m-%d %H:%M') : Criado a tabela ${relacionamento}" > log/$(echo ${relacionamento})-log

   sqlite3 $BANCO "INSERT INTO ${relacionamento} VALUES (null, 1,1 )"
   sqlite3 $BANCO "INSERT INTO ${relacionamento} VALUES (null, 1,7 )"
   sqlite3 $BANCO "INSERT INTO ${relacionamento} VALUES (null, 5,2 )"
   sqlite3 $BANCO "INSERT INTO ${relacionamento} VALUES (null, 2,3 )"
   sqlite3 $BANCO "INSERT INTO ${relacionamento} VALUES (null, 3,5 )"
   sqlite3 $BANCO "INSERT INTO ${relacionamento} VALUES (null, 7,3 )"

  

   sqlite3 -column -header $BANCO "CREATE VIEW ${relacionamento:+v$relacionamento} AS SELECT * FROM  ${tabela} 
   JOIN ${relacionamento}
   ON ${tabela}.id=${relacionamento}.${tabela}_id 
   JOIN ${relacao} 
   ON ${relacao}.id=${relacionamento}.${relacao}_id" 

   echo "$(date +'%Y-%m-%d %H:%M') : Criado a view ${relacionamento:+v$relacionamento}" >> log/$(echo ${relacionamento})-log
   sqlite3 -column -header $BANCO "SELECT * FROM ${relacionamento:+v$relacionamento}" >> log/$(echo ${relacionamento})-log
}
relaciona
