#!/usr/bin/env bash

BANCO='../database/agenda.db'
TABELA='usuario'
MSG_USO="
Uso: $0 [ OPÇÃO ]

OPEÇÃO: 
    -c | --cadastrar  - Cadastro de usuario
    -r | --remover    - Remover usuario
    -l | --listar     - listar usuario 
    -b | --buscar     - busca de usuario
    -a | --atualizar  - login obrigatorio para atualizar
"
source ../Lib/_crud

_pega-dados(){
    read -p 'Digite o login: ' login
    read -s -p 'Digite o senha: ' senha
    if [[  "$login" = 'teste' &&  "$senha" = '123'  ]];then

      echo 'true'
      exit 1 
    fi
}

cadastrar(){
  for i in 1 2 3
  do
    _pega-dados
    echo -e '\n\n' 
    echo "falha no login $i/3 "
  done
    #echo  "login: $login senha: $senha"
}

remover(){
    echo "Remover de usuario"
    _all login| sed 's/\n / - /g' 
    echo "Digite o login do usuario que sera removido: "
    read usuario
    _delete $usuario
}

listar(){
    echo "Listar de usuario"
    _find
}

buscar(){
    echo "Digite o login"
    read usuario
    _find $usuario
}

atualizar(){
    buscar 
}

case $1 in
    -c | --cadastrar) cadastrar ;;
    -r | --remover) remover ;;
    -l | --listar) listar ;;
    -b | --buscar) buscar ;;
    -a | --atualizar) atualizar ;;

    *)
        echo "$MSG_USO"
esac
