#!/usr/bin/env bash

BANCO='../database/agenda.db'
TABELA='usuario'
MSG_USO="
Uso: $0 [ OPÇÃO ]

OPEÇÃO: 
    -c | --cadastrar - Cadastro de usuario
    -r | --remover - Remover usuario
    -l | --listar - listar usuario 
    -b | --buscar - busca de usuario
    -a | --atualizar - login obrigatorio para atualizar
"
source ../Lib/_crud
source ../Lib/_ux

_pega-dados(){
    login=$(_ux 2 'Cadastro de Usuaro' ' Digite o login')
    [  "$(_tem $login )" ] || {
        return 1
    }
    nome=$(_ex  'Cadastro de Usuaro' ' Digite o nome')
    nome=$(echo "$nome" | sed 's/ /+/g')
    idade=$(_ux 2 'Cadastro de Usuaro' ' Digite o idade')
    echo -n "Digite o sexo: "
    read sexo
}

cadastrar(){
    _pega-dados
    _insert $login $nome $idade $sexo
}

remover(){
    echo "Remover de usuario"
    _all login| sed 's/\n / - /g' 
    usuario=$(_ux 2 'Cadastro de Usuaro' ' Digite o login que sera removido')
    _delete $usuario
}

listar(){
    echo "Listar de usuario"
    _find
}

buscar(){
    usuario=$(_ux 'Cadastro de Usuaro' ' Digite o login')
    _find $usuario
}

atualizar(){
    buscar 
}

case $1 in
    -c | --cadastrar) cadastrar ;;
    -r | --remover) remover ;;
    -l | --listar) listar ;;
    -b | --buscar) buscar ;;
    -a | --atualizar) atualizar ;;

    *)
        echo "$MSG_USO"
esac
