#!/usr/bin/env bash
BANCO='../database/agenda.db'
TABELA='login'
source ../Lib/_ux

logar(){
  senha=$(echo "$2" | shasum | cut -d' ' -f1)
  sql="SELECT * FROM $TABELA WHERE login='$1' AND senha='$senha'"
  echo "$sql"
  
  logado=$(sqlite3 $BANCO "$sql") 
  [ "$logado" ] && {
    _ux 1 'Logado'  "Bem vindo '$1'"
  } || {
    _ux 1  'Acesso  restrito' ''
    exit 1
  }
}

nome=$(_ux 2 'Nome' 'Digite seu nome' 'Autenticação')
senha=$(_ux 3 'Senha' 'Digite sua senha' 'Autenticação')

logar "$nome" "$senha"
