#!/usr/bin/env bash

[ "$BANCO"  ] || {
    echo "Set o caminho do banco na variavel 'BANCO' "
    exit 1
}

[ "$TABELA"  ] || {
    echo "Informe a TABELA na variavel 'TABELA'"
    exit 1
}

_campos(){
    campos=($(_all | sed -n 1p | sed 's/|/ /g' ))
    qto=${#campos[@]}
}

_all(){
    local sql="SELECT * FROM $TABELA " 
    [ ! "$1" ] || {
        sql="SELECT $1 FROM $TABELA "
    }
    sqlite3 -header $BANCO "$sql"
}

_find(){
    _campos
    local sql="SELECT * FROM $TABELA " 
    [ ! "$1" ] || {
        sql+="WHERE ${campos[1]}='$1'"
    }
    
    sqlite3 "$BANCO" "$sql"
}

_tem(){
    tem=$(_find $1 | cut -d '|' -f2)
    [ -n "$tem" ] || {
      echo 'Epa! não tem ninguem com esse nome'
        return 1
    }
}

_delete(){
    _campos
    _tem $1
    local sql="DELETE FROM $TABELA WHERE ${campos[0]}='$tem';" 
    sqlite3 "$BANCO" "$sql"
    msg="$TABELA '$tem' limado !!"
}

_insert(){
    _campos
    [[ "$#" -eq "$qto"  ]] || {
        echo "Esta faltando informação! "
        return 1
    }
    local valor=$(echo "$@" | sed "s/ /', '/g;s/.*/'&'/") 
    valor=$(echo "$valor" | sed 's/+/ /g')  
    local field=$(echo "${campos[@]}" | sed 's/ /, /g')
    local sql="INSERT INTO $TABELA ( $field ) VALUES ( $valor ); "
    sqlite3 "$BANCO" "$sql"
    msg="'$1' inserido com sucesso !!"
}

_update(){
    _campos
    _tem "$1" 
    [  "$tem" ] || return 1
    [[ "$qto" -ge "$#" ]] || {
        echo "Excedeu a quantidade de campos de '$TABELA'"
        return 1
    }
    local valor=($@)  
    for ((i=1; i<="$qto"; i++ )){
        local set+=" ${campos[$i]}='${valor[$i]}'"  
    }
    set=$(echo "$set" |  sed "s/=''$//g;s/ //;s/ /, /g")
    set=$(echo $set | sed 's/+/ /g;s/,$//')
    local sql="update $TABELA set $set where ${campos[0]}='$1' "
    echo "$sql"
    sqlite3 "$BANCO" "$sql"
    echo "'$1' atualizado com sucesso !!"
}
